---
- name: users | find current jetty-all jar file.
  find:
    file_type: file
    paths: "{{ rundeck_home_dir }}/bootstrap"
    patterns: "^jetty-all-.*"
    use_regex: True
  register: rundeck_jetty_jar

- name: users | encode users password
  shell: "java -cp {{ rundeck_jetty_jar['files'][0]['path'] }} org.eclipse.jetty.util.security.Password {{ item.name }} {{ item.password }} 2>&1 | grep MD5"
  become: True
  register: rundeck_encoded_users
  when: rundeck_users|length > 0 and rundeck_jetty_jar['matched'] > 0
  with_items: "{{ rundeck_users }}"

- name: users | update basic security to have users
  template:
    src: realm.properties.j2
    dest: /etc/rundeck/realm.properties
    owner: rundeck
    group: rundeck
  when: rundeck_users|length > 0 and rundeck_encoded_users|success
  notify:
    - restart rundeck
  tags:
    - rundeck
    - users
